name: 'CI/CD Pipeline'

on:
   push:
    branches:
        - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Operations
      working-directory: infra
      run: |
        terraform init -reconfigure
        terraform fmt -check
        terraform plan -input=false
        terraform apply -auto-approve -input=false
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    - name: Terraform Output
      working-directory: infra
      run: terraform output
    